#!/usr/bin/env php
<?php
defined('STDIN') or die('This script is meant to be ran from the shell.');

require_once dirname(__FILE__).'/deploki.php';
Deploki::prepareEnvironment();
$options = DeplokiOptions::loadFrom(Deploki::locateConfig());

$deploki = new Deploki($config);
$deploki->deploy($config->pages);
